if(OPENCL_SDK_BUILD_SAMPLES)
  foreach(DEP IN ITEMS cargs TCLAP Stb)
    list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/Dependencies/${DEP}")
    include(${DEP})
  endforeach()

  if(OPENCL_SDK_BUILD_OPENGL_SAMPLES)
    foreach(DEP IN ITEMS X11 glm OpenGL GLEW SFML)
      list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/Dependencies/${DEP}")
      include(${DEP})
    endforeach()
    if(TARGET libglew_static)
      message(STATUS libglew_static exists)
    endif()
  endif(OPENCL_SDK_BUILD_OPENGL_SAMPLES)
endif(OPENCL_SDK_BUILD_SAMPLES)